artifact_location: file:C:/Users/ASUS/OneDrive/Desktop/Eksperimen_SML_Rapika Rosalia
  Depari/db_mlflow/109989514458365327
creation_time: 1780132912068
experiment_id: '109989514458365327'
last_update_time: 1780132912068
lifecycle_stage: active
name: Eksperimen_Pistachio_Rapika
trace_location: null
workspace: default
