artifact_uri: file:C:/Users/ASUS/OneDrive/Desktop/Eksperimen_SML_Rapika Rosalia Depari/db_mlflow/109989514458365327/7fa11d87bcce41a9b538dbf0c451e712/artifacts
end_time: 1780132937593
entry_point_name: ''
experiment_id: '109989514458365327'
lifecycle_stage: active
run_id: 7fa11d87bcce41a9b538dbf0c451e712
run_name: Model_Random_Forest_Awal
source_name: ''
source_type: 4
source_version: ''
start_time: 1780132912456
status: 3
tags: []
user_id: ASUS
